### ISSUE TITLE
密码是什么呀？

### ISSUE THREAD

**Issue by Johnson-IT** [IcedSoul/tiny-heart#1]

**Comment by IcedSoul** [comment]
ReadMe里面有写。
https://github.com/IcedSoul/tiny-heart/tree/master/birthday-basic

**Comment by Johnson-IT** [comment]
非常感谢！




------------------ 原始邮件 ------------------
发件人: "Xiaofeng Guo"<notifications@github.com>; 
发送时间: 2019年8月2日(星期五) 晚上7:37
收件人: "IcedSoul/tiny-heart"<tiny-heart@noreply.github.com>; 
抄送: "Emperor"<631956794@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [IcedSoul/tiny-heart] 密码是什么呀？ (#1)




ReadMe里面有写。
 https://github.com/IcedSoul/tiny-heart/tree/master/birthday-basic
